FontAwesomeParser:
  modifiers:
    size:
      code: 'x'
      arguments: true
    spin:
      code: 'spin'
      arguments: false
    rotate:
      code: 'rotate-'
      arguments: true
    flip:
      code: 'flip-'
      arguments: true