Firesphere\FontAwesome\FontAwesomeParser:
  modifiers:
    size:
      code: '%sx'
      arguments: true
    spin:
      code: 'spin'
      arguments: false
    rotate:
      code: 'rotate-%s'
      arguments: true
    flip:
      code: 'flip-%s'
      arguments: true